export const summary01 = [
  {
    capture: 'The Right to Shelter Mandate in New York City',
    text: "New York City has a right to shelter mandate that dates back to the 1980s. The state supreme court ordered the city to provide shelter to anyone in need. However, critics argue that if this issue is as significant as the mayor and other officials claim, they should amend the process for handling such situations. The right to shelter is expensive, leading to controversial cuts in education and police funding. The mayor suggests that wealthier residents should contribute more money to avoid these cuts. Some fear this could lead to increased taxes. The budget cuts ordered by Mayor Adams are unpopular, especially those affecting the police, fire department, and public schools. The city claims it lacks funds, but it actually has $2.1 billion in uncollected fees and violations. These funds could be used to support schools, police, libraries, and parks. The budget cuts also impact New York City's parks department, resulting in the loss of over 1,400 jobs. This includes the parks opportunity program, which provides employment and training to New Yorkers looking to improve their skills and economic situation. The program helps individuals without a high school diploma and offers education to obtain a high school equivalency degree. Critics argue that it is more cost-effective to pay individuals to maintain the parks than to spend $400 a day on shelter for the homeless. The loss of this program will lead to a decline in park cleanliness and a negative impact on the city's neediest residents.",
  },
  {
    capture: "Concerns for New York City's Parks",
    text: "The budget cuts to the parks department will have a significant impact on New York City's parks. The loss of over 1,400 jobs, including those in the parks opportunity program, will result in a decline in park maintenance and cleanliness. The parks opportunity program provides employment and training to individuals, offering them a chance to improve their skills and economic situation. The program also helps individuals without a high school diploma by providing education to obtain a high school equivalency degree. The loss of this program will not only affect park cleanliness but also hinder the economic progress of those who rely on it. The parks will likely see an increase in trash and a decline in the quality of park facilities, such as bathrooms. This will have a negative impact on park visitors and the overall perception of the city's parks. Critics argue that the cost of maintaining the parks through the parks opportunity program is more cost-effective than spending $400 a day on shelter for the homeless. The loss of this program will not only result in a decline in park cleanliness but also hinder the economic progress of those who rely on it.",
  },
  {
    capture: 'The Impact on New Yorkers and the City',
    text: "The budget cuts in New York City will have a significant impact on both the residents and the city as a whole. The loss of funding for education, police, and parks will negatively affect the quality of life for New Yorkers. The cuts to education will harm students and hinder their future prospects. The cuts to the police department will result in increased crime rates and a decline in public safety. The cuts to the parks department will lead to a decline in park cleanliness and maintenance, affecting the overall experience for park visitors. Additionally, the loss of over 1,400 jobs, including those in the parks opportunity program, will have a devastating impact on the individuals who rely on these jobs for their livelihood. The city claims it lacks funds, but the existence of $2.1 billion in uncollected fees and violations raises questions about the city's financial management. The budget cuts are seen as a short-sighted solution that will do more harm than good in the long run. The concerns raised by New Yorkers highlight the need for alternative solutions to address the city's financial challenges without sacrificing essential services and programs.",
  },
]
