import { ICategory } from '../Interfaces/ICategory'

export const CATEGORIES: ICategory[] = [
  { icon: 'BsHouseDoor', en: 'house', ru: '' },
  { icon: 'AiOutlineShoppingCart', en: '', ru: '' },
  { icon: 'AiOutlineMedicineBox', en: '', ru: '' },
  { icon: 'AiFillCar', en: '', ru: '' },
  { icon: 'MdFlightTakeoff', en: '', ru: '' },
  { icon: 'MdBusinessCenter', en: '', ru: '' },
  { icon: 'MdOutlineMeetingRoom', en: '', ru: '' },
  { icon: 'MdComputer', en: '', ru: '' },
  { icon: 'AiOutlineBank', en: '', ru: '' },
  { icon: 'BsFillPiggyBankFill', en: '', ru: '' },
  { icon: 'AiOutlineIdcard', en: '', ru: '' },
  { icon: 'HiOutlineAcademicCap', en: '', ru: '' },
  { icon: 'BsFlower2', en: '', ru: '' },
  { icon: 'MdOutlineLocalShipping', en: '', ru: '' },
  { icon: 'FaShip', en: '', ru: '' },
  { icon: 'MdCardTravel', en: '', ru: '' },
  { icon: 'FaCampground', en: '', ru: '' },
  { icon: 'AiOutlineGift', en: '', ru: '' },
  { icon: 'MdElderly', en: '', ru: '' },
  { icon: 'MdFastfood', en: '', ru: '' },
  { icon: 'BiCookie', en: '', ru: '' },
  { icon: 'FaMotorcycle', en: '', ru: '' },
  { icon: 'BiBuildingHouse', en: '', ru: '' },
  { icon: 'FaDog', en: '', ru: '' },
  { icon: 'FaCat', en: '', ru: '' },
  { icon: 'MdSportsBar', en: '', ru: '' },
  { icon: 'MdDesignServices', en: '', ru: '' },
  { icon: 'FaHeadSideMask', en: '', ru: '' },
  { icon: 'FaTheaterMasks', en: '', ru: '' },
  { icon: 'AiFillApple', en: '', ru: '' },
  { icon: 'BsMicrosoft', en: '', ru: '' },
  { icon: 'FaLinux', en: '', ru: '' },
  { icon: 'IoLogoJavascript', en: '', ru: '' },
  { icon: 'IoLogoPython', en: '', ru: '' },
  { icon: 'FaPhp', en: '', ru: '' },
  { icon: 'SiMysql', en: '', ru: '' },
  { icon: '', en: '', ru: '' },
  { icon: '', en: '', ru: '' },
  { icon: '', en: '', ru: '' },
  { icon: '', en: '', ru: '' },
  { icon: '', en: '', ru: '' },
]
