import { ICategory } from '../Interfaces/ICategory'

export const CATEGORIES: ICategory[] = [
  { icon: 'BsHouseDoor', en: 'house', ru: 'недвижимость' },
  { icon: 'AiOutlineShoppingCart', en: 'shopping', ru: 'шопинг' },
  { icon: 'AiOutlineMedicineBox', en: 'medicine', ru: 'здоровье, лечение' },
  { icon: 'AiFillCar', en: 'cars', ru: 'автомобили' },
  { icon: 'MdFlightTakeoff', en: 'flights', ru: 'полеты на самолете' },
  { icon: 'MdBusinessCenter', en: 'business', ru: 'бизнес' },
  { icon: 'MdOutlineMeetingRoom', en: 'meeting online', ru: 'онлайн общение' },
  { icon: 'MdComputer', en: 'computer', ru: 'компьютер' },
  { icon: 'AiOutlineBank', en: 'banking', ru: 'банковские услуги' },
  { icon: 'BsFillPiggyBankFill', en: 'finance', ru: 'финансы' },
  { icon: 'AiOutlineIdcard', en: 'bank cards', ru: 'банковские карты' },
  { icon: 'HiOutlineAcademicCap', en: 'education', ru: 'образование' },
  { icon: 'BsFlower2', en: 'gardening', ru: 'садоводство' },
  { icon: 'MdOutlineLocalShipping', en: 'shipping', ru: 'перевозка логистика' },
  { icon: 'FaShip', en: 'ships', ru: 'яхты катера' },
  { icon: 'MdCardTravel', en: 'travelling', ru: 'путешествия' },
  {
    icon: 'FaCampground',
    en: 'camping hiking',
    ru: 'походы, отдых за городом',
  },
  { icon: 'AiOutlineGift', en: 'gifts', ru: 'подарки' },
  { icon: 'MdElderly', en: 'elderly people care', ru: 'пожилые люди, уход' },
  { icon: 'MdFastfood', en: 'nutrition', ru: 'питание' },
  { icon: 'BiCookie', en: 'food', ru: 'продукты' },
  { icon: 'FaMotorcycle', en: 'motorcycles', ru: 'мотоциклы' },
  { icon: 'BiBuildingHouse', en: 'construction', ru: 'строительство' },
  { icon: 'FaDog', en: 'house pets', ru: 'домашние животные, собаки' },
  { icon: 'FaCat', en: 'cats', ru: 'кошки' },
  { icon: 'MdSportsBar', en: 'bar crawling', ru: 'бары и отдых' },
  { icon: 'MdDesignServices', en: 'house design', ru: 'дизайн интерьера' },
  { icon: 'FaHeadSideMask', en: 'covid 19', ru: 'ковид 19' },
  { icon: 'FaTheaterMasks', en: 'theaters', ru: 'театры' },
  { icon: 'AiFillApple', en: 'Apple', ru: 'Apple' },
  { icon: 'BsMicrosoft', en: 'Microsoft', ru: 'Microsoft' },
  { icon: 'FaLinux', en: 'Linux', ru: 'Linux' },
  { icon: 'IoLogoJavascript', en: 'Javascript', ru: 'Javascript' },
  { icon: 'IoLogoPython', en: 'Python', ru: 'Python' },
  { icon: 'FaPhp', en: 'PHP', ru: 'PHP' },
  { icon: 'SiMysql', en: 'MySQL', ru: 'MySQL' },
  { icon: '', en: '', ru: '' },
]
