export const CATEGORIES_TO_EXCHANGE: Record<
  string,
  { en: string; ru: string }
> = {
  // _: { en: '_', ru: '_' },
  Autoclub: { en: 'Autoclub', ru: 'Автоклуб' },
  Auto_flea_market: { en: 'Auto flea market', ru: 'Автобарахолка' },
  Auto_parts_and_repair: {
    en: 'Auto parts and repair',
    ru: 'Автозапчасти и ремонт',
  },
  Bankruptcy: { en: 'Bankruptcy', ru: 'Банкротство' },
  Bankruptcy_of_individuals: {
    en: 'Bankruptcy of individuals',
    ru: 'Банкротство физических лиц',
  },
  Insolvency_manager: {
    en: 'Insolvency manager',
    ru: 'Арбитражное управление',
  },
  Car_audio_and_multimedia: {
    en: 'Car audio and multimedia',
    ru: 'Автозвук и мультимедиа',
  },
  Washing_machine: { en: 'Washing machine', ru: 'Стиральная машина' },
  Photoshop: { en: 'Photoshop', ru: 'Фотошоп' },
  Metal_ladder: { en: 'Metal ladder', ru: 'Лестницы из металла' },
  Buying_and_selling_cars: {
    en: 'Buying and selling cars',
    ru: 'Покупка и продажа автомобилей',
  },
  Styling_tuning_xenon: {
    en: 'Styling tuning xenon',
    ru: 'Стайлинг тюнинг ксенон',
  },
  Tires_and_rims: { en: 'Tires and rims', ru: 'Шины и диски' },
  Auto_right: { en: 'Auto right', ru: 'Автоправо' },
  Auto_insurance: { en: 'Auto insurance', ru: 'Автострахование' },
  Road_accident: { en: 'Road accident', ru: 'ДТП' },
  Communication_with_the_traffic_police: {
    en: 'Communication with the traffic police',
    ru: 'Общение с ГИБДД',
  },
  Other_auto_legal_issues: {
    en: 'Other auto-legal issues',
    ru: 'Прочие автоправовые вопросы',
  },
  Foreign_cars: { en: 'Foreign cars', ru: 'Иномарки' },
  Clubs_of_foreign_cars: { en: 'Clubs of foreign cars', ru: 'Клубы иномарок' },
  American_cars: { en: 'American cars', ru: 'American cars' },
  Bmw: { en: 'Bmw', ru: 'BMW ' },
  KIA: { en: 'KIA', ru: 'KIA ' },
  Nissan: { en: 'Nissan', ru: 'Nissan' },
  Subaru: { en: 'Subaru', ru: 'Subaru' },
  Skoda: { en: 'Skoda', ru: 'Skoda ' },
  SUZUKI: { en: 'SUZUKI', ru: 'SUZUKI' },
  Toyota: { en: 'Toyota', ru: 'Toyota  ' },
  VolksWagen: { en: 'VolksWagen', ru: 'VolksWagen' },
  Honda_Pilots_Club: { en: 'Honda Pilots Club', ru: 'Клуб Honda Pilots' },
  French_growers_club: { en: 'French growers club', ru: 'Клуб французоводов' },
  Mazda: { en: 'Mazda', ru: 'МАЗДА' },
  Matiz_club: { en: 'Matiz club', ru: 'Матиз клуб' },
  Chevrolet_club: { en: 'Chevrolet club', ru: 'Шевроле клуб' },
  Communication_of_foreign_car_owners: {
    en: 'Communication of foreign car owners',
    ru: 'Общение владельцев иномарок',
  },
  Communication_of_foreign_cars_clubs: {
    en: 'Communication of foreign cars clubs',
    ru: 'Общение клубов иномарок',
  },
  Motor_forums: { en: 'Motor forums', ru: 'Мотофорумы' },
  ATVs_Snowmobiles: { en: 'ATVs & Snowmobiles', ru: 'Квадроциклы и снегоходы' },
  Motorcycle_club: { en: 'Motorcycle club', ru: 'Мотоклуб' },
  Scooter_club: { en: 'Scooter club', ru: 'Скутерклуб' },
  Autoradioclub: { en: 'Autoradioclub', ru: 'Авторадиоклуб' },
  Motorsport: { en: 'Motorsport', ru: 'Автоспорт' },
  Trucks_and_special_equipment: {
    en: 'Trucks and special equipment',
    ru: 'Грузовики и спецтехника',
  },
  Autoclub_communication: {
    en: 'Autoclub communication',
    ru: 'Общение Автоклуба',
  },
  General_automotive_issues: {
    en: 'General automotive issues',
    ru: 'Общие автомобильные вопросы',
  },
  Russian_cars: { en: 'Russian cars', ru: 'Российские автомобили' },
  House: { en: 'House', ru: 'Дом' },
  Real_estate: { en: 'Real estate', ru: 'Недвижимость' },
  Exchange_Bureau: { en: 'Exchange Bureau', ru: 'Обменбюро' },
  Communication_of_neighbors: {
    en: 'Communication of neighbors',
    ru: 'Общение соседей',
  },
  Construction_and_design: {
    en: 'Construction and design',
    ru: 'Строительство и дизайн',
  },
  Design_landscape_interior: {
    en: 'Design landscape interior',
    ru: 'Дизайн ландшафт интерьер',
  },
  Construction_market: { en: 'Construction market', ru: 'Строительный рынок' },
  Construction_and_repair: {
    en: 'Construction and repair',
    ru: 'Строительство и ремонт',
  },
  Animals: { en: 'Animals', ru: 'Животные' },
  Into_good_hands_We_will_help_you_in_any_way_we_can: {
    en: 'Into good hands We will help you in any way we can',
    ru: 'В добрые руки Поможем чем сможем',
  },
  Into_the_good_hands_of_the_cat: {
    en: 'Into the good hands of the cat',
    ru: 'В добрые руки кошки',
  },
  In_good_hands_other_animals: {
    en: 'In good hands, other animals',
    ru: 'В добрые руки прочая живность',
  },
  In_the_good_hands_of_the_dog: {
    en: 'In the good hands of the dog',
    ru: 'В добрые руки собаки',
  },
  We_will_help_you_in_any_way_we_can: {
    en: 'We will help you in any way we can',
    ru: 'Поможем чем сможем',
  },
  Zoomarket: { en: 'Zoomarket', ru: 'Зоомаркет' },
  Buying_and_selling_other_animals: {
    en: 'Buying and selling other animals',
    ru: 'Покупка и продажа другой живности',
  },
  Buying_and_selling_cats: {
    en: 'Buying and selling cats',
    ru: 'Покупка и продажа кошек',
  },
  Buying_and_selling_dogs: {
    en: 'Buying and selling dogs',
    ru: 'Покупка и продажа собак',
  },
  Aquarium_and_terrarium_management: {
    en: 'Aquarium and terrarium management',
    ru: 'Аквариумистика и террариумистика',
  },
  Home_farm: { en: 'Home farm', ru: 'Домашняя ферма' },
  Horses_and_riding: { en: 'Horses and riding', ru: 'Лошади и верховая езда' },
  Animal_lovers_communication: {
    en: 'Animal lovers communication',
    ru: 'Общение любителей животных',
  },
  Health: { en: 'Health', ru: 'Здоровье' },
  Pregnancy_and_Childbirth: {
    en: 'Pregnancy and Childbirth',
    ru: 'Беременность и Роды',
  },
  Children_s_health: { en: "Children's health", ru: 'Детское здоровье' },
  Culture: { en: 'Culture', ru: 'Культура' },
  Poster: { en: 'Poster', ru: 'Афиша' },
  Cinema: { en: 'Cinema', ru: 'Кино' },
  Books: { en: 'Books', ru: 'Книги' },
  Culture_personality_and_society: {
    en: 'Culture personality and society',
    ru: 'Культура личность и общество',
  },
  Music: { en: 'Music', ru: 'Музыка' },
  Society: { en: 'Society', ru: 'Общество' },
  Kids_club: { en: 'Kids club', ru: 'Детский клуб' },
  Preschoolers_from_3_to_7_years_old: {
    en: 'Preschoolers from 3 to 7 years old',
    ru: 'Дошколята от 3 до 7 лет',
  },
  Lyalki_from_0_to_1_year: {
    en: 'Lyalki from 0 to 1 year',
    ru: 'Ляльки от 0 до 1 года',
  },
  Toddlers_from_1_to_3_years_old: {
    en: 'Toddlers from 1 to 3 years old',
    ru: 'Малыши от 1 до 3 лет',
  },
  Anonymous: { en: 'Anonymous', ru: 'Анонимный' },
  Children_and_Parents: { en: 'Children and Parents', ru: 'Дети и Родители' },
  Womens_Club: { en: "Women's Club", ru: 'Женский клуб' },
  Coronavirus_Covid19: {
    en: 'Coronavirus Covid19',
    ru: 'Коронавирус  Covid19',
  },
  Mens_club: { en: "Men's club", ru: 'Мужской клуб' },
  Politics: { en: 'Politics', ru: 'Политика' },
  Legal_issues: { en: 'Legal issues', ru: 'Правовые вопросы' },
  Plants: { en: 'Plants', ru: 'Растения' },
  Wedding: { en: 'Wedding', ru: 'Свадьба' },
  Family_relationships: {
    en: 'Family relationships',
    ru: 'Семейные отношения',
  },
  Jelly: { en: 'Jelly', ru: 'Студень' },
  Creation: { en: 'Creation', ru: 'Творчество' },
  Recreation: { en: 'Recreation', ru: 'Отдых' },
  Acquaintance: { en: 'Acquaintance', ru: 'Знакомства' },
  Club_culture: { en: 'Club culture', ru: 'Клубная культура' },
  Cooking: { en: 'Cooking', ru: 'Кулинария' },
  Around_the_World_Discussion: {
    en: 'Around the World Discussion',
    ru: 'Обсуждение Кругосветки',
  },
  Leisure_and_travel: { en: 'Leisure and travel', ru: 'Отдых и путешествия' },
  Radio: { en: 'Radio', ru: 'Радио ' },
  Restaurants_cafes_and_gastronomy: {
    en: 'Restaurants cafes and gastronomy',
    ru: 'Рестораны кафе и гастрономия',
  },
  Dance_floor: { en: 'Dance floor', ru: 'Танцплощадка' },
  Party: { en: 'Party', ru: 'Тусовка' },
  Work: { en: 'Work', ru: 'Работа' },
  HR_community: { en: 'HR community', ru: 'HRсообщество' },
  Education: { en: 'Education', ru: 'Образование' },
  Work_and_career: { en: 'Work and career', ru: 'Работа и карьера' },
  Remote_work_freelance: {
    en: 'Remote work freelance',
    ru: 'Удаленная работа фриланс',
  },
  Joint_purchase: { en: 'Joint purchase', ru: 'Совместная покупка' },
  Everyday_life: { en: 'Everyday life', ru: 'Быт' },
  Adult_shoes: { en: 'Adult shoes', ru: 'Взрослая обувь' },
  Adult_clothing_and_accessories: {
    en: 'Adult clothing and accessories',
    ru: 'Взрослая одежда и аксессуары',
  },
  Childrens_shoes: { en: "Children's shoes", ru: 'Детская обувь' },
  Childrens_clothing_and_accessories: {
    en: "Children's clothing and accessories",
    ru: 'Детская одежда и аксессуары',
  },
  Childrens_miscellaneous: {
    en: "Children's miscellaneous",
    ru: 'Детское разное',
  },
  Food: { en: 'Food', ru: 'Продукты питания' },
  Joint_purchase_order_collection: {
    en: 'Joint purchase order collection',
    ru: 'Совметная покупка сбор заказов',
  },
  Joint_purchase_of_accessories: {
    en: 'Joint purchase of accessories',
    ru: 'Совметная покупка аксессуары',
  },
  Joint_purchase_orders_from_foreign_sites: {
    en: 'Joint purchase orders from foreign sites',
    ru: 'Совметная покупка заказы с иностранных сайтов',
  },
  Joint_purchase_of_shoes: {
    en: 'Joint purchase of shoes',
    ru: 'Совметная покупка обувь',
  },
  Collective_purchase_of_clothes: {
    en: 'Collective purchase of clothes',
    ru: 'Совметная покупка одежда',
  },
  Joint_purchase_of_perfumery_and_cosmetics: {
    en: 'Joint purchase of perfumery and cosmetics',
    ru: 'Совметная покупка парфюмерия и косметика',
  },
  Joint_purchase_of_food: {
    en: 'Joint purchase of food',
    ru: 'Совметная покупка продукты питания',
  },
  Joint_purchase_of_goods_for_children: {
    en: 'Joint purchase of goods for children',
    ru: 'Совметная покупка товары для детей',
  },
  Joint_purchase_of_household_goods: {
    en: 'Joint purchase of household goods',
    ru: 'Совметная покупка товары для дома',
  },
  Joint_purchase_of_goods_for_animals: {
    en: 'Joint purchase of goods for animals',
    ru: 'Совметная покупка товары для животных',
  },
  Joint_purchase_of_a_service: {
    en: 'Joint purchase of a service',
    ru: 'Совметная покупка услуги',
  },
  Joint_purchase_rules_general_questions: {
    en: 'Joint purchase rules general questions',
    ru: 'Совметная покупка правила общие вопросы',
  },
  Joint_purchase_distribution_of_orders: {
    en: 'Joint purchase distribution of orders',
    ru: 'Совметная покупка раздача заказов',
  },
  Collective_purchase_collection_of_payment: {
    en: 'Collective purchase collection of payment',
    ru: 'Совметная покупка сбор оплаты',
  },
  Joint_purchase_reconciliation: {
    en: 'Joint purchase reconciliation',
    ru: 'Совметная покупка сверка',
  },
  Joint_purchase_show_off_purchases: {
    en: 'Joint purchase show off purchases!',
    ru: 'Совметная покупка хвастаемся покупками!',
  },
  Sport: { en: 'Sport', ru: 'Спорт' },
  Winter_sports: { en: 'Winter sports', ru: 'Зимние виды спорта' },
  Winter_sports_communication: {
    en: 'Winter sports communication',
    ru: 'Общение Зимних видов спорта',
  },
  Buying_and_selling_equipment: {
    en: 'Buying and selling equipment',
    ru: 'Покупка и продажа снаряжения',
  },
  Spin_the_pedals: { en: 'Spin the pedals!', ru: 'Крути педали!' },
  Cycling: { en: 'Cycling', ru: 'Велоспорт' },
  Cycling_tourism: { en: 'Cycling tourism', ru: 'Велотуризм' },
  Cyclist_communication: {
    en: 'Cyclist communication',
    ru: 'Общение велосипедистов',
  },
  Buying_and_selling_bicycles_and_parts: {
    en: 'Buying and selling bicycles and parts',
    ru: 'Покупка и продажа велосипедов и запчастей',
  },
  Jogging_aerobics_fitness_yoga: {
    en: 'Jogging aerobics fitness yoga',
    ru: 'Бег аэробика фитнес йога',
  },
  Bodimaster: { en: 'Bodimaster', ru: 'Бодимастер' },
  Martial_arts: { en: 'Martial arts', ru: 'Боевые искусства' },
  Windsurfing: { en: 'Windsurfing', ru: 'Виндсерфинг' },
  Volleyball: { en: 'Volleyball', ru: 'Волейбол' },
  Game_sports: { en: 'Game sports', ru: 'Игровые виды спорта' },
  Games: { en: 'Games', ru: 'Игры' },
  Hunting: { en: 'Hunting', ru: 'Охота' },
  Paragliders_and_kites: {
    en: 'Paragliders and kites',
    ru: 'Парапланы и кайты',
  },
  Diving: { en: 'Diving', ru: 'Подводное плавание' },
  Fishing: { en: 'Fishing', ru: 'Рыбалка' },
  Amateur_tourism_and_local_history: {
    en: 'Amateur tourism and local history',
    ru: 'Самодеятельный туризм и краеведение',
  },
  Shooting_club: { en: 'Shooting club', ru: 'Стрелковый клуб' },
  Football: { en: 'Football', ru: 'Футбол' },
  Extreme_sport: { en: 'Extreme sport', ru: 'Экстремальный спорт' },
  Technologies: { en: 'Technologies', ru: 'Технологии' },
  Gadgets: { en: 'Gadgets', ru: 'Гаджеты' },
  Discussion_of_gadgets: {
    en: 'Discussion of gadgets',
    ru: 'Обсуждение гаджетов',
  },
  Buying_and_selling_gadgets: {
    en: 'Buying and selling gadgets',
    ru: 'Покупка и продажа гаджетов',
  },
  Internet: { en: 'Internet', ru: 'Интернет' },
  Yekaterinburg_providers: {
    en: 'Yekaterinburg providers',
    ru: 'Екатеринбургские провайдеры',
  },
  Programming_and_design: {
    en: 'Programming and design',
    ru: 'Программирование и дизайн',
  },
  mobile_connection: { en: 'mobile connection', ru: 'Мобильная связь' },
  Mobile_accessories_and_numbers: {
    en: 'Mobile accessories and numbers',
    ru: 'Мобильные аксессуары и номера',
  },
  Phone_Models: { en: 'Phone Models', ru: 'Модели телефонов' },
  Operators: { en: 'Operators', ru: 'Операторы' },
  Sale_and_purchase_of_mobile_phones: {
    en: 'Sale and purchase of mobile phones',
    ru: 'Продажа и покупка мобильных телефонов',
  },
  Technical_Issues: { en: 'Technical Issues', ru: 'Технические вопросы' },
  UNIX_Linux_Open_Source_Software: {
    en: 'UNIX Linux Open Source Software',
    ru: 'UNIX Linux Open Source Software',
  },
  Technical_questions_iron: {
    en: 'Technical questions iron',
    ru: 'Технические вопросы железо',
  },
  Software_technical_issues: {
    en: 'Software technical issues',
    ru: 'Технические вопросы софт',
  },
  The_photo: { en: 'The photo', ru: 'Фотография' },
  Discussion_of_photos: {
    en: 'Discussion of photos',
    ru: 'Обсуждение фотографий',
  },
  IP_telephony: { en: 'IP telephony', ru: 'IPтелефония' },
  Banking_technologies: {
    en: 'Banking technologies',
    ru: 'Банковские технологии',
  },
  Appliances: { en: 'Appliances', ru: 'Бытовая техника' },
  Video_editing: { en: 'Video editing', ru: 'Видеомонтаж' },
  Questions_about_the_work_of_1C: {
    en: 'Questions about the work of 1C',
    ru: 'Вопросы по работе 1С',
  },
  Sound_Recording_Mixing_Mastering: {
    en: 'Sound Recording Mixing Mastering',
    ru: 'Звукозапись Сведение Мастеринг',
  },
  Modeling: { en: 'Modeling', ru: 'Моделизм' },
  Industrial_zone: { en: 'Industrial zone', ru: 'Промзона' },
  Radio_amateur: { en: 'Radio amateur', ru: 'Радиолюбитель' },
  Economy: { en: 'Economy', ru: 'Экономика' },
  Advertising_marketing_PR: {
    en: 'Advertising marketing PR',
    ru: 'Реклама маркетинг PR',
  },
  Practical_advice: { en: 'Practical advice', ru: 'Практические советы' },
  Advertising_community: {
    en: 'Advertising community',
    ru: 'Рекламное сообщество',
  },
  Discussion_news: { en: 'Discussion news', ru: 'Обсуждение новостей' },
  all_skills: {
    en: 'all skills',
    ru: 'все навыки',
  },
}
