import { CategoryType } from '../Interfaces/CategoryType'

export const CATEGORIES: CategoryType[] = [
  { icon: 'BsHouseDoor', en: 'House', ru: 'Недвижимость' },
  { icon: 'AiOutlineShoppingCart', en: 'Shopping', ru: 'Щопинг' },
  { icon: 'AiOutlineMedicineBox', en: 'Medicine', ru: 'Здоровье, лечение' },
  { icon: 'AiFillCar', en: 'Cars', ru: 'Автомобили' },
  { icon: 'MdFlightTakeoff', en: 'Flights', ru: 'Полеты самолеты' },
  { icon: 'MdBusinessCenter', en: 'Business', ru: 'Бизнес' },
  { icon: 'MdOutlineMeetingRoom', en: 'Meeting online', ru: 'Онлайн общение' },
  { icon: 'MdComputer', en: 'Computer', ru: 'Компьютер' },
  { icon: 'AiOutlineBank', en: 'Banking', ru: 'Банковские услуги' },
  { icon: 'BsFillPiggyBankFill', en: 'Finance', ru: 'Финансы' },
  { icon: 'AiOutlineIdcard', en: 'Bank cards', ru: 'Банковские карты' },
  { icon: 'HiOutlineAcademicCap', en: 'Education', ru: 'Образование' },
  { icon: 'BsFlower2', en: 'Gardening', ru: 'Садоводство' },
  { icon: 'MdOutlineLocalShipping', en: 'Shipping', ru: 'Перевозки логистика' },
  { icon: 'FaShip', en: 'Yachts ships', ru: 'Яхты катера' },
  { icon: 'MdCardTravel', en: 'Travelling', ru: 'Путешествия' },
  {
    icon: 'FaCampground',
    en: 'Camping hiking',
    ru: 'Походы, отдых за городом',
  },
  { icon: 'AiOutlineGift', en: 'Gifts', ru: 'Подарки' },
  { icon: 'MdElderly', en: 'Elderly people care', ru: 'Пожилые люди, уход' },
  { icon: 'MdFastfood', en: 'Nutrition', ru: 'Питание' },
  { icon: 'BiCookie', en: 'Food', ru: 'Продукты' },
  { icon: 'FaMotorcycle', en: 'Motorcycles', ru: 'Мотоциклы' },
  { icon: 'BiBuildingHouse', en: 'Construction', ru: 'Строительство' },
  { icon: 'FaDog', en: 'House pets', ru: 'Домашние животные, собаки' },
  { icon: 'FaCat', en: 'Cats', ru: 'Кошки' },
  { icon: 'MdSportsBar', en: 'Bar crawling', ru: 'Бары и отдых' },
  { icon: 'MdDesignServices', en: 'House design', ru: 'Дизайн интерьера' },
  { icon: 'FaHeadSideMask', en: 'Covid 19', ru: 'Ковид 19' },
  { icon: 'FaTheaterMasks', en: 'Tßheaters', ru: 'Театры' },
  { icon: '', en: '', ru: '' },
]
