import {
  MdSportsBar,
  MdDesignServices,
  MdFastfood,
  MdElderly,
  MdCardTravel,
  MdOutlineLocalShipping,
  MdComputer,
  MdOutlineMeetingRoom,
  MdBusinessCenter,
  MdFlightTakeoff,
  MdAddBox,
  MdAddShoppingCart,
  MdBlock,
  MdClose,
  MdContactMail,
  MdFlag,
  MdForward,
  MdHome,
  MdLanguage,
  MdMailOutline,
  MdMenu,
  MdPause,
  MdPerson,
  MdPlayArrow,
  MdPrint,
  MdQueue,
  MdRemoveCircle,
  MdSearch,
} from 'react-icons/md'

import {
  AiFillApple,
  AiOutlineGift,
  AiOutlineIdcard,
  AiOutlineBank,
  AiFillCar,
  AiOutlineMedicineBox,
  AiOutlineShoppingCart,
  AiOutlineQuestionCircle,
} from 'react-icons/ai'
import { BiBuildingHouse, BiCookie, BiSelectMultiple } from 'react-icons/bi'
import {
  BsMicrosoft,
  BsFlower2,
  BsFillPiggyBankFill,
  BsHouseDoor,
  BsLink45Deg,
  BsQuestionCircle,
} from 'react-icons/bs'
import { CgDarkMode } from 'react-icons/cg'
import {
  FaPhp,
  FaLinux,
  FaTheaterMasks,
  FaHeadSideMask,
  FaCat,
  FaDog,
  FaMotorcycle,
  FaCampground,
  FaShip,
  FaFacebook,
  FaVk,
  FaTwitter,
  FaGooglePlusG,
} from 'react-icons/fa'
import { HiOutlineAcademicCap } from 'react-icons/hi'
import {
  IoLogoPython,
  IoLogoJavascript,
  IoChatbubblesOutline,
} from 'react-icons/io5'

import { ICONS_PROGRAMMING } from './iconsSimple.const'

export const ICONS = {
  ...ICONS_PROGRAMMING,
  FaPhp,
  IoLogoPython,
  IoLogoJavascript,
  FaLinux,
  BsMicrosoft,
  AiFillApple,
  FaTheaterMasks,
  FaHeadSideMask,
  MdSportsBar,
  MdDesignServices,
  FaCat,
  FaDog,
  BiBuildingHouse,
  FaMotorcycle,
  BiCookie,
  MdFastfood,
  MdElderly,
  AiOutlineGift,
  FaCampground,
  MdCardTravel,
  FaShip,
  MdOutlineLocalShipping,
  BsFlower2,
  AiOutlineIdcard,
  BsFillPiggyBankFill,
  AiOutlineBank,
  MdComputer,
  MdOutlineMeetingRoom,
  MdBusinessCenter,
  MdFlightTakeoff,
  AiFillCar,
  AiOutlineMedicineBox,
  AiOutlineShoppingCart,
  BsHouseDoor,
  AiOutlineQuestionCircle,
  BiSelectMultiple,
  BsLink45Deg,
  BsQuestionCircle,
  CgDarkMode,
  FaFacebook,
  FaGooglePlusG,
  FaTwitter,
  FaVk,
  HiOutlineAcademicCap,
  IoChatbubblesOutline,
  MdAddBox,
  MdAddShoppingCart,
  MdBlock,
  MdClose,
  MdContactMail,
  MdFlag,
  MdForward,
  MdHome,
  MdLanguage,
  MdMailOutline,
  MdMenu,
  MdPause,
  MdPerson,
  MdPlayArrow,
  MdPrint,
  MdQueue,
  MdRemoveCircle,
  MdSearch,
}
