import {
  MdHomeRepairService,
  MdConnectWithoutContact,
  MdDevicesOther,
  MdPhonelinkSetup,
  MdOpenInBrowser,
  MdArrowRight,
  MdKeyboardArrowRight,
  MdSportsBar,
  MdDesignServices,
  MdFastfood,
  MdElderly,
  MdCardTravel,
  MdOutlineLocalShipping,
  MdComputer,
  MdOutlineMeetingRoom,
  MdBusinessCenter,
  MdFlightTakeoff,
  MdAddBox,
  MdAddShoppingCart,
  MdBlock,
  MdClose,
  MdContactMail,
  MdFlag,
  MdForward,
  MdHome,
  MdLanguage,
  MdMailOutline,
  MdMenu,
  MdPause,
  MdPerson,
  MdPlayArrow,
  MdPrint,
  MdQueue,
  MdRemoveCircle,
  MdSearch,
} from 'react-icons/md'

import {
  AiFillCloseCircle,
  AiOutlineSetting,
  AiOutlineShareAlt,
  AiFillApple,
  AiOutlineGift,
  AiOutlineIdcard,
  AiOutlineBank,
  AiFillCar,
  AiOutlineMedicineBox,
  AiOutlineShoppingCart,
  AiOutlineQuestionCircle,
} from 'react-icons/ai'

import {
  BiVideoPlus,
  BiBuildingHouse,
  BiCookie,
  BiSelectMultiple,
} from 'react-icons/bi'

import {
  BsFillPersonPlusFill,
  BsFillPersonCheckFill,
  BsPiggyBank,
  BsMicrosoft,
  BsFlower2,
  BsFillPiggyBankFill,
  BsHouseDoor,
  BsLink45Deg,
  BsQuestionCircle,
} from 'react-icons/bs'

import { CgDarkMode } from 'react-icons/cg'

import {
  FaExchangeAlt,
  FaChalkboardTeacher,
  FaUsers,
  FaUserCheck,
  FaUsersCog,
  FaRegSmileWink,
  FaTheaterMasks,
  FaHeadSideMask,
  FaCat,
  FaDog,
  FaMotorcycle,
  FaCampground,
  FaShip,
  FaFacebook,
  FaVk,
  FaTwitter,
  FaGooglePlusG,
} from 'react-icons/fa'

import { HiUsers, HiOutlineAcademicCap } from 'react-icons/hi'

import {
  IoLanguageSharp,
  IoLogoPython,
  IoLogoJavascript,
  IoChatbubblesOutline,
} from 'react-icons/io5'

import { RiVoiceprintFill } from 'react-icons/ri'

import { SiAppstore, SiGoogleplay } from 'react-icons/si'

import { ICONS_PROGRAMMING } from './iconsSimple.const'

export const ICONS = {
  ...ICONS_PROGRAMMING,
  FaExchangeAlt,
  FaChalkboardTeacher,
  BsFillPersonPlusFill,
  AiFillCloseCircle,
  BiVideoPlus,
  FaUsers,
  MdHomeRepairService,
  IoLanguageSharp,
  FaUserCheck,
  FaUsersCog,
  BsFillPersonCheckFill,
  HiUsers,
  AiOutlineShareAlt,
  BsPiggyBank,
  SiAppstore,
  SiGoogleplay,
  FaRegSmileWink,
  AiOutlineSetting,
  MdConnectWithoutContact,
  RiVoiceprintFill,
  MdDevicesOther,
  MdPhonelinkSetup,
  MdOpenInBrowser,
  MdArrowRight,
  MdKeyboardArrowRight,
  IoLogoPython,
  IoLogoJavascript,
  BsMicrosoft,
  AiFillApple,
  FaTheaterMasks,
  FaHeadSideMask,
  MdSportsBar,
  MdDesignServices,
  FaCat,
  FaDog,
  BiBuildingHouse,
  FaMotorcycle,
  BiCookie,
  MdFastfood,
  MdElderly,
  AiOutlineGift,
  FaCampground,
  MdCardTravel,
  FaShip,
  MdOutlineLocalShipping,
  BsFlower2,
  AiOutlineIdcard,
  BsFillPiggyBankFill,
  AiOutlineBank,
  MdComputer,
  MdOutlineMeetingRoom,
  MdBusinessCenter,
  MdFlightTakeoff,
  AiFillCar,
  AiOutlineMedicineBox,
  AiOutlineShoppingCart,
  BsHouseDoor,
  AiOutlineQuestionCircle,
  BiSelectMultiple,
  BsLink45Deg,
  BsQuestionCircle,
  CgDarkMode,
  FaFacebook,
  FaGooglePlusG,
  FaTwitter,
  FaVk,
  HiOutlineAcademicCap,
  IoChatbubblesOutline,
  MdAddBox,
  MdAddShoppingCart,
  MdBlock,
  MdClose,
  MdContactMail,
  MdFlag,
  MdForward,
  MdHome,
  MdLanguage,
  MdMailOutline,
  MdMenu,
  MdPause,
  MdPerson,
  MdPlayArrow,
  MdPrint,
  MdQueue,
  MdRemoveCircle,
  MdSearch,
}
