/**
 * @description Language codes to use in HTML documents (see the pages for the hrefLang, lang and xml:lang attributes)
 * @link http://help.dottoro.com/lahffigx.php
 */
export const LANGUAGE = [
  { code: 'af', description: 'Afrikaans', isActive: false },
  { code: 'sq', description: 'Albanian', isActive: false },
  { code: 'ar-dz', description: 'Arabic (Algeria)', isActive: false },
  { code: 'ar-bh', description: 'Arabic (Bahrain)', isActive: false },
  { code: 'ar-eg', description: 'Arabic (Egypt)', isActive: false },
  { code: 'ar-iq', description: 'Arabic (Iraq)', isActive: false },
  { code: 'ar-jo', description: 'Arabic (Jordan)', isActive: false },
  { code: 'ar-kw', description: 'Arabic (Kuwait)', isActive: false },
  { code: 'ar-lb', description: 'Arabic (Lebanon)', isActive: false },
  { code: 'ar-ly', description: 'Arabic (Libya)', isActive: false },
  { code: 'ar-ma', description: 'Arabic (Morocco)', isActive: false },
  { code: 'ar-om', description: 'Arabic (Oman)', isActive: false },
  { code: 'ar-qa', description: 'Arabic (Qatar)', isActive: false },
  { code: 'ar-sa', description: 'Arabic (SaudiArabia)', isActive: false },
  { code: 'ar-sy', description: 'Arabic (Syria)', isActive: false },
  { code: 'ar-tn', description: 'Arabic (Tunisia)', isActive: false },
  { code: 'ar-ae', description: 'Arabic (U.A.E.)', isActive: false },
  { code: 'ar-ye', description: 'Arabic (Yemen)', isActive: false },
  { code: 'eu', description: 'Basque', isActive: false },
  { code: 'be', description: 'Belarusian', isActive: false },
  { code: 'bg', description: 'Bulgarian', isActive: false },
  { code: 'ca', description: 'Catalan', isActive: false },
  { code: 'zh-hk', description: 'Chinese (HongKongSAR)', isActive: false },
  { code: 'zh-cn', description: 'Chinese (PRC)', isActive: false },
  { code: 'zh-sg', description: 'Chinese (Singapore)', isActive: false },
  { code: 'zh-tw', description: 'Chinese (Taiwan)', isActive: false },
  { code: 'hr', description: 'Croatian', isActive: false },
  { code: 'cs', description: 'Czech', isActive: false },
  { code: 'da', description: 'Danish', isActive: false },
  { code: 'nl-be', description: 'Dutch (Belgium)', isActive: false },
  { code: 'nl', description: 'Dutch (Standard)', isActive: false },
  { code: 'en', description: 'English', isActive: false },
  { code: 'en-au', description: 'English (Australia)', isActive: false },
  { code: 'en-bz', description: 'English (Belize)', isActive: false },
  { code: 'en-ca', description: 'English (Canada)', isActive: false },
  { code: 'en-ie', description: 'English (Ireland)', isActive: false },
  { code: 'en-jm', description: 'English (Jamaica)', isActive: false },
  { code: 'en-nz', description: 'English (NewZealand)', isActive: false },
  { code: 'en-za', description: 'English (SouthAfrica)', isActive: false },
  { code: 'en-tt', description: 'English (Trinidad)', isActive: false },
  { code: 'en-gb', description: 'English (UnitedKingdom)', isActive: false },
  { code: 'en-us', description: 'English (UnitedStates)', isActive: true },
  { code: 'et', description: 'Estonian', isActive: false },
  { code: 'fo', description: 'Faeroese', isActive: false },
  { code: 'fa', description: 'Farsi', isActive: false },
  { code: 'fi', description: 'Finnish', isActive: false },
  { code: 'fr-be', description: 'French (Belgium)', isActive: false },
  { code: 'fr-ca', description: 'French (Canada)', isActive: false },
  { code: 'fr-lu', description: 'French (Luxembourg)', isActive: false },
  { code: 'fr', description: 'French (Standard)', isActive: false },
  { code: 'fr-ch', description: 'French (Switzerland)', isActive: false },
  { code: 'mk', description: 'FYROMacedonian', isActive: false },
  { code: 'gd-ie', description: 'Gaelic (Ireland)', isActive: false },
  { code: 'gd', description: 'Gaelic (Scotland)', isActive: false },
  { code: 'de-at', description: 'German (Austria)', isActive: false },
  { code: 'de-li', description: 'German (Liechtenstein)', isActive: false },
  { code: 'de-lu', description: 'German (Luxembourg)', isActive: false },
  { code: 'de', description: 'German (Standard)', isActive: false },
  { code: 'de-ch', description: 'German (Switzerland)', isActive: false },
  { code: 'el', description: 'Greek', isActive: false },
  { code: 'he', description: 'Hebrew', isActive: false },
  { code: 'hi', description: 'Hindi', isActive: false },
  { code: 'hu', description: 'Hungarian', isActive: false },
  { code: 'is', description: 'Icelandic', isActive: false },
  { code: 'id', description: 'Indonesian', isActive: false },
  { code: 'it', description: 'Italian (Standard)', isActive: false },
  { code: 'it-ch', description: 'Italian (Switzerland)', isActive: false },
  { code: 'ja', description: 'Japanese', isActive: false },
  { code: 'ko', description: 'Korean', isActive: false },
  { code: 'lv', description: 'Latvian', isActive: false },
  { code: 'lt', description: 'Lithuanian', isActive: false },
  { code: 'ms', description: 'Malaysian', isActive: false },
  { code: 'mt', description: 'Maltese', isActive: false },
  { code: 'no', description: 'Norwegian', isActive: false },
  { code: 'pl', description: 'Polish', isActive: false },
  { code: 'pt-br', description: 'Portuguese (Brazil)', isActive: false },
  { code: 'pt', description: 'Portuguese (Portugal)', isActive: false },
  { code: 'rm', description: 'Rhaeto-Romanic', isActive: false },
  { code: 'ro', description: 'Romanian', isActive: false },
  { code: 'ro-mo', description: 'Romanian (Moldavia)', isActive: false },
  { code: 'ru', description: 'Russian', isActive: true },
  { code: 'ru-mo', description: 'Russian (Moldavia)', isActive: false },
  { code: 'sz', description: 'Sami (Lappish)', isActive: false },
  { code: 'sr', description: 'Serbian', isActive: false },
  { code: 'sk', description: 'Slovak', isActive: false },
  { code: 'sl', description: 'Slovenian', isActive: false },
  { code: 'sb', description: 'Sorbian', isActive: false },
  { code: 'es-ar', description: 'Spanish (Argentina)', isActive: false },
  { code: 'es-bo', description: 'Spanish (Bolivia)', isActive: false },
  { code: 'es-cl', description: 'Spanish (Chile)', isActive: false },
  { code: 'es-co', description: 'Spanish (Colombia)', isActive: false },
  { code: 'es-cr', description: 'Spanish (CostaRica)', isActive: false },
  {
    code: 'es-do',
    description: 'Spanish (DominicanRepublic)',
    isActive: false,
  },
  { code: 'es-ec', description: 'Spanish (Ecuador)', isActive: false },
  { code: 'es-sv', description: 'Spanish (ElSalvador)', isActive: false },
  { code: 'es-gt', description: 'Spanish (Guatemala)', isActive: false },
  { code: 'es-hn', description: 'Spanish (Honduras)', isActive: false },
  { code: 'es-mx', description: 'Spanish (Mexico)', isActive: false },
  { code: 'es-ni', description: 'Spanish (Nicaragua)', isActive: false },
  { code: 'es-pa', description: 'Spanish (Panama)', isActive: false },
  { code: 'es-py', description: 'Spanish (Paraguay)', isActive: false },
  { code: 'es-pe', description: 'Spanish (Peru)', isActive: false },
  { code: 'es-pr', description: 'Spanish (PuertoRico)', isActive: false },
  { code: 'es', description: 'Spanish', isActive: false },
  { code: 'es-uy', description: 'Spanish (Uruguay)', isActive: false },
  { code: 'es-ve', description: 'Spanish (Venezuela)', isActive: false },
  { code: 'sx', description: 'Sutu', isActive: false },
  { code: 'sv', description: 'Swedish', isActive: false },
  { code: 'sv-fi', description: 'Swedish (Finland)', isActive: false },
  { code: 'th', description: 'Thai', isActive: false },
  { code: 'ts', description: 'Tsonga', isActive: false },
  { code: 'tn', description: 'Tswana', isActive: false },
  { code: 'tr', description: 'Turkish', isActive: false },
  { code: 'uk', description: 'Ukrainian', isActive: false },
  { code: 'ur', description: 'Urdu', isActive: false },
  { code: 've', description: 'Venda', isActive: false },
  { code: 'vi', description: 'Vietnamese', isActive: false },
  { code: 'xh', description: 'Xhosa', isActive: false },
  { code: 'ji', description: 'Yiddish', isActive: false },
  { code: 'zu', description: 'Zulu', isActive: false },
]
