/**
 * @description Language codes to use in HTML documents (see the pages for the hrefLang, lang and xml:lang attributes)
 * @link http://help.dottoro.com/lahffigx.php
 */
export const LANGUAGE = [
  { code: 'af', description: 'Afrikaans', active: false },
  { code: 'sq', description: 'Albanian', active: false },
  { code: 'ar-dz', description: 'Arabic (Algeria)', active: false },
  { code: 'ar-bh', description: 'Arabic (Bahrain)', active: false },
  { code: 'ar-eg', description: 'Arabic (Egypt)', active: false },
  { code: 'ar-iq', description: 'Arabic (Iraq)', active: false },
  { code: 'ar-jo', description: 'Arabic (Jordan)', active: false },
  { code: 'ar-kw', description: 'Arabic (Kuwait)', active: false },
  { code: 'ar-lb', description: 'Arabic (Lebanon)', active: false },
  { code: 'ar-ly', description: 'Arabic (Libya)', active: false },
  { code: 'ar-ma', description: 'Arabic (Morocco)', active: false },
  { code: 'ar-om', description: 'Arabic (Oman)', active: false },
  { code: 'ar-qa', description: 'Arabic (Qatar)', active: false },
  { code: 'ar-sa', description: 'Arabic (SaudiArabia)', active: false },
  { code: 'ar-sy', description: 'Arabic (Syria)', active: false },
  { code: 'ar-tn', description: 'Arabic (Tunisia)', active: false },
  { code: 'ar-ae', description: 'Arabic (U.A.E.)', active: false },
  { code: 'ar-ye', description: 'Arabic (Yemen)', active: false },
  { code: 'eu', description: 'Basque', active: false },
  { code: 'be', description: 'Belarusian', active: false },
  { code: 'bg', description: 'Bulgarian', active: false },
  { code: 'ca', description: 'Catalan', active: false },
  { code: 'zh-hk', description: 'Chinese (HongKongSAR)', active: false },
  { code: 'zh-cn', description: 'Chinese (PRC)', active: false },
  { code: 'zh-sg', description: 'Chinese (Singapore)', active: false },
  { code: 'zh-tw', description: 'Chinese (Taiwan)', active: false },
  { code: 'hr', description: 'Croatian', active: false },
  { code: 'cs', description: 'Czech', active: false },
  { code: 'da', description: 'Danish', active: false },
  { code: 'nl-be', description: 'Dutch (Belgium)', active: false },
  { code: 'nl', description: 'Dutch (Standard)', active: false },
  { code: 'en', description: 'English', active: false },
  { code: 'en-au', description: 'English (Australia)', active: false },
  { code: 'en-bz', description: 'English (Belize)', active: false },
  { code: 'en-ca', description: 'English (Canada)', active: false },
  { code: 'en-ie', description: 'English (Ireland)', active: false },
  { code: 'en-jm', description: 'English (Jamaica)', active: false },
  { code: 'en-nz', description: 'English (NewZealand)', active: false },
  { code: 'en-za', description: 'English (SouthAfrica)', active: false },
  { code: 'en-tt', description: 'English (Trinidad)', active: false },
  { code: 'en-gb', description: 'English (UnitedKingdom)', active: false },
  { code: 'en-us', description: 'English (UnitedStates)', active: true },
  { code: 'et', description: 'Estonian', active: false },
  { code: 'fo', description: 'Faeroese', active: false },
  { code: 'fa', description: 'Farsi', active: false },
  { code: 'fi', description: 'Finnish', active: false },
  { code: 'fr-be', description: 'French (Belgium)', active: false },
  { code: 'fr-ca', description: 'French (Canada)', active: false },
  { code: 'fr-lu', description: 'French (Luxembourg)', active: false },
  { code: 'fr', description: 'French (Standard)', active: false },
  { code: 'fr-ch', description: 'French (Switzerland)', active: false },
  { code: 'mk', description: 'FYROMacedonian', active: false },
  { code: 'gd-ie', description: 'Gaelic (Ireland)', active: false },
  { code: 'gd', description: 'Gaelic (Scotland)', active: false },
  { code: 'de-at', description: 'German (Austria)', active: false },
  { code: 'de-li', description: 'German (Liechtenstein)', active: false },
  { code: 'de-lu', description: 'German (Luxembourg)', active: false },
  { code: 'de', description: 'German (Standard)', active: false },
  { code: 'de-ch', description: 'German (Switzerland)', active: false },
  { code: 'el', description: 'Greek', active: false },
  { code: 'he', description: 'Hebrew', active: false },
  { code: 'hi', description: 'Hindi', active: false },
  { code: 'hu', description: 'Hungarian', active: false },
  { code: 'is', description: 'Icelandic', active: false },
  { code: 'id', description: 'Indonesian', active: false },
  { code: 'it', description: 'Italian (Standard)', active: false },
  { code: 'it-ch', description: 'Italian (Switzerland)', active: false },
  { code: 'ja', description: 'Japanese', active: false },
  { code: 'ko', description: 'Korean', active: false },
  { code: 'lv', description: 'Latvian', active: false },
  { code: 'lt', description: 'Lithuanian', active: false },
  { code: 'ms', description: 'Malaysian', active: false },
  { code: 'mt', description: 'Maltese', active: false },
  { code: 'no', description: 'Norwegian', active: false },
  { code: 'pl', description: 'Polish', active: false },
  { code: 'pt-br', description: 'Portuguese (Brazil)', active: false },
  { code: 'pt', description: 'Portuguese (Portugal)', active: false },
  { code: 'rm', description: 'Rhaeto-Romanic', active: false },
  { code: 'ro', description: 'Romanian', active: false },
  { code: 'ro-mo', description: 'Romanian (Moldavia)', active: false },
  { code: 'ru', description: 'Russian', active: true },
  { code: 'ru-mo', description: 'Russian (Moldavia)', active: false },
  { code: 'sz', description: 'Sami (Lappish)', active: false },
  { code: 'sr', description: 'Serbian', active: false },
  { code: 'sk', description: 'Slovak', active: false },
  { code: 'sl', description: 'Slovenian', active: false },
  { code: 'sb', description: 'Sorbian', active: false },
  { code: 'es-ar', description: 'Spanish (Argentina)', active: false },
  { code: 'es-bo', description: 'Spanish (Bolivia)', active: false },
  { code: 'es-cl', description: 'Spanish (Chile)', active: false },
  { code: 'es-co', description: 'Spanish (Colombia)', active: false },
  { code: 'es-cr', description: 'Spanish (CostaRica)', active: false },
  { code: 'es-do', description: 'Spanish (DominicanRepublic)', active: false },
  { code: 'es-ec', description: 'Spanish (Ecuador)', active: false },
  { code: 'es-sv', description: 'Spanish (ElSalvador)', active: false },
  { code: 'es-gt', description: 'Spanish (Guatemala)', active: false },
  { code: 'es-hn', description: 'Spanish (Honduras)', active: false },
  { code: 'es-mx', description: 'Spanish (Mexico)', active: false },
  { code: 'es-ni', description: 'Spanish (Nicaragua)', active: false },
  { code: 'es-pa', description: 'Spanish (Panama)', active: false },
  { code: 'es-py', description: 'Spanish (Paraguay)', active: false },
  { code: 'es-pe', description: 'Spanish (Peru)', active: false },
  { code: 'es-pr', description: 'Spanish (PuertoRico)', active: false },
  { code: 'es', description: 'Spanish', active: false },
  { code: 'es-uy', description: 'Spanish (Uruguay)', active: false },
  { code: 'es-ve', description: 'Spanish (Venezuela)', active: false },
  { code: 'sx', description: 'Sutu', active: false },
  { code: 'sv', description: 'Swedish', active: false },
  { code: 'sv-fi', description: 'Swedish (Finland)', active: false },
  { code: 'th', description: 'Thai', active: false },
  { code: 'ts', description: 'Tsonga', active: false },
  { code: 'tn', description: 'Tswana', active: false },
  { code: 'tr', description: 'Turkish', active: false },
  { code: 'uk', description: 'Ukrainian', active: false },
  { code: 'ur', description: 'Urdu', active: false },
  { code: 've', description: 'Venda', active: false },
  { code: 'vi', description: 'Vietnamese', active: false },
  { code: 'xh', description: 'Xhosa', active: false },
  { code: 'ji', description: 'Yiddish', active: false },
  { code: 'zu', description: 'Zulu', active: false },
]
