export const courseSuccess = {
  courseID: 'wBvQba1DI1Y',
  capture: '2-s Исторические деятели России и СССР первой половины XX века',
  description:
    'Кратко и емко в запоминающейся форме о деятелях России и СССР первой половины XX века',
  language: 'ru',
  isActive: true,
  dateCreated: 1640995200000,
  dateUpdated: 1640995200000,
  dateDeleted: null,
  meta: {
    institution: 'Студия "Городок"',
    specTitle: 'Специалист Oтдела Мировой Истории',
    specName: 'Олег Приколов',
    email: 't3531350@yahoo.com',
    isSendingBcc: false,
    __typename: 'MetaType',
  },
  modules: [
    {
      moduleID: 'wBvQba1DI1Y',
      index: 0,
      isActive: true,
      contentType: 'ytID',
      contentID: 'wBvQba1DI1Y',
      capture: 'Модуль I',
      duration: '2:36',
      questionNumber: 4,
      passRate: 0.75,
      questions: [
        {
          questionID: 'f57K1Bix-mL2yv0dPCHn3',
          capture: 'Согласно текста самодержец Николка',
          isActive: true,
          options: [
            {
              optionID: 'm7b06SkEXsUeKTdqZGktd',
              label: 'был внешностью красив',
              status: false,
              __typename: 'OptionType',
              answer: false,
            },
            {
              optionID: 'h9gzTtCaHzMI1XGtGCkGj',
              label: 'был выдающейся личностью в истории',
              status: false,
              __typename: 'OptionType',
              answer: false,
            },
            {
              optionID: 'vg4KYvcD4GUfkCQ1epWtn',
              label: 'не видел дальше носа своего',
              status: true,
              __typename: 'OptionType',
              answer: true,
            },
            {
              optionID: 'EsPdRxp15IgJMVHunIYhU',
              label: 'правил так, что было что закусить',
              status: true,
              __typename: 'OptionType',
              answer: true,
            },
          ],
          __typename: 'QuestionType',
        },
        {
          questionID: 'So7p0H0T4ocJYGGja2ThF',
          capture: 'Согласно услышанного при товарище Сталине...',
          isActive: true,
          options: [
            {
              optionID: '9enqrC_cftsI10BN4WEMm',
              label: 'в лагеря загнали всех',
              status: true,
              __typename: 'OptionType',
              answer: true,
            },
            {
              optionID: 'NVC0AlBzEFtNPD0VWtGKB',
              label: 'строились ТЭЦ',
              status: true,
              __typename: 'OptionType',
              answer: true,
            },
            {
              optionID: 'DYzYfKlmAkytre3SLXADs',
              label: 'граждан жизни не лишали',
              status: false,
              __typename: 'OptionType',
              answer: false,
            },
            {
              optionID: 'tAy1QI83XWaUfe57GKVRv',
              label: 'колхозы распустили',
              status: false,
              __typename: 'OptionType',
              answer: false,
            },
          ],
          __typename: 'QuestionType',
        },
        {
          questionID: 'XBRzzstUVyUW9ZCr5gcKr',
          capture: 'Согласно песни Микитушка...',
          isActive: true,
          options: [
            {
              optionID: 'vc1BhUCnMyLFsJ6inwnz2',
              label: 'пихал (космонавтов) на Луну',
              status: true,
              __typename: 'OptionType',
              answer: true,
            },
            {
              optionID: 'KypCs9xPKG6gqbwgWJ3jB',
              label: 'наградил Кеннади медалью',
              status: false,
              __typename: 'OptionType',
              answer: false,
            },
            {
              optionID: 'm-GtjOJWw_j7QNVxdRdxE',
              label: 'был невысого роста',
              status: true,
              __typename: 'OptionType',
              answer: true,
            },
            {
              optionID: 'SWsMarKIlAvZsVw3tj5Kh',
              label: 'совершил немного дел',
              status: false,
              __typename: 'OptionType',
              answer: false,
            },
          ],
          __typename: 'QuestionType',
        },
      ],
      __typename: 'ModuleType',
    },
  ],
  __typename: 'CourseType',
  searchString:
    'исторические деятели россии и ссср первой половины xx века кратко и емко в запоминающейся форме о деятелях россии и ссср первой половины xx века модуль i  согласно текста самодержец николка был внешностью красив был выдающейся личностью в истории не видел дальше носа своего правил так, что было что закусить согласно услышанного при товарище сталине... в лагеря загнали всех строились тэц граждан жизни не лишали колхозы распустили согласно песни микитушка... пихал (космонавтов) на луну наградил кеннади медалью был невысого роста совершил немного дел',
}
