import {
  MdAddShoppingCart,
  MdArrowBackIos,
  MdArrowForwardIos,
  MdArrowRight,
  MdAssignmentTurnedIn,
  MdCastForEducation,
  MdCheck,
  MdCheckBoxOutlineBlank,
  MdCheckCircle,
  MdClear,
  MdClose,
  MdContactMail,
  MdDeleteOutline,
  MdFlag,
  MdForward,
  MdHome,
  MdLightbulbOutline,
  MdLogin,
  MdLogout,
  MdMailOutline,
  MdMenu,
  MdOutlineReplay,
  MdOutlineSend,
  MdOutlineVideocam,
  MdPause,
  MdPerson,
  MdPlayArrow,
  MdPrint,
  MdQueue,
  MdRemoveCircle,
  MdSearch,
} from 'react-icons/md'

import { BsFillPersonPlusFill, BsLink45Deg } from 'react-icons/bs'

import { CgDarkMode } from 'react-icons/cg'

import {
  FaChalkboardTeacher,
  FaHatWizard,
  FaMoon,
  FaRegSun,
  FaUserAstronaut,
  FaUserCheck,
  FaUserCircle,
  FaUserCog,
  FaUserEdit,
  FaUserGraduate,
  FaUserLock,
  FaUserMd,
  FaUserMinus,
  FaUserNinja,
  FaUserPlus,
  FaUserShield,
  FaUserSlash,
  FaUserTie,
} from 'react-icons/fa'

import { FaWandMagicSparkles, FaMountainSun } from 'react-icons/fa6'

import { GiSnake } from 'react-icons/gi'

import { HiOutlineAcademicCap } from 'react-icons/hi'

export const ICONS = {
  BsFillPersonPlusFill,
  BsLink45Deg,
  CgDarkMode,
  FaChalkboardTeacher,
  FaHatWizard,
  FaMoon,
  FaMountainSun,
  FaRegSun,
  FaUserAstronaut,
  FaUserCheck,
  FaUserCircle,
  FaUserCog,
  FaUserEdit,
  FaUserGraduate,
  FaUserLock,
  FaUserMd,
  FaUserMinus,
  FaUserNinja,
  FaUserPlus,
  FaUserShield,
  FaUserSlash,
  FaUserTie,
  FaWandMagicSparkles,
  GiSnake,
  HiOutlineAcademicCap,
  MdAddShoppingCart,
  MdArrowBackIos,
  MdArrowForwardIos,
  MdArrowRight,
  MdAssignmentTurnedIn,
  MdCastForEducation,
  MdCheck,
  MdCheckBoxOutlineBlank,
  MdCheckCircle,
  MdClear,
  MdClose,
  MdContactMail,
  MdDeleteOutline,
  MdFlag,
  MdForward,
  MdHome,
  MdLightbulbOutline,
  MdLogin,
  MdLogout,
  MdMailOutline,
  MdMenu,
  MdOutlineReplay,
  MdOutlineSend,
  MdOutlineVideocam,
  MdPause,
  MdPerson,
  MdPlayArrow,
  MdPrint,
  MdQueue,
  MdRemoveCircle,
  MdSearch,
}
