import { Reducer, Action, ReducersMapObject } from 'redux'

import { RootStoreType } from '../Interfaces/RootStoreType'

import { TEMPLATE } from './reducers/TEMPLATE'
import { SET_IS_LOADED_LOCAL_STORAGE_STORE_STATE } from './reducers/SET_IS_LOADED_LOCAL_STORAGE_STORE_STATE'
import { ADD_DOCUMENT } from './reducers/ADD_DOCUMENT'
import { CHANGE_NUM_QUESTIONS_IN_SLIDE } from './reducers/CHANGE_NUM_QUESTIONS_IN_SLIDE'
import { CLICK_CHECK } from './reducers/CLICK_CHECK'
import { GET_ANSWERS_DEFAULT } from './reducers/GET_ANSWERS_DEFAULT'
import { GET_AVATAR_PATH } from './reducers/GET_AVATAR_PATH'
import { GET_COGNITO_TOKENS_SUCCESS } from './reducers/GET_COGNITO_TOKENS_SUCCESS'
import { GET_COURSE_QUERY_PR_QN } from './reducers/GET_COURSE_QUERY_PR_QN'
import { GET_COURSES_SUCCESS } from './reducers/GET_COURSES_SUCCESS'
import { ONCHANGE_EMAIL_CC } from './reducers/ONCHANGE_EMAIL_CC'
import { ONCHANGE_EMAIL_TO } from './reducers/ONCHANGE_EMAIL_TO'
import { ONCHANGE_FIRST_NAME_MODAL } from './reducers/ONCHANGE_FIRST_NAME_MODAL'
import { ONCHANGE_LAST_NAME_MODAL } from './reducers/ONCHANGE_LAST_NAME_MODAL'
import { ONCHANGE_MIDDLE_NAME_MODAL } from './reducers/ONCHANGE_MIDDLE_NAME_MODAL'
import { ONCHANGE_SEARCH_INPUT } from './reducers/ONCHANGE_SEARCH_INPUT'
import { ONCHANGE_USER_BIRTH_YEAR } from './reducers/ONCHANGE_USER_BIRTH_YEAR'
import { ONCHANGE_USER_EMAIL } from './reducers/ONCHANGE_USER_EMAIL'
import { ONCHANGE_USER_INFO_ABOUT } from './reducers/ONCHANGE_USER_INFO_ABOUT'
import { ONCHANGE_USER_NAME } from './reducers/ONCHANGE_USER_NAME'
import { ONCHANGE_USER_NAME_FIRST } from './reducers/ONCHANGE_USER_NAME_FIRST'
import { ONCHANGE_USER_NAME_NICK } from './reducers/ONCHANGE_USER_NAME_NICK'
import { ONCHANGE_USER_PASSWORD_AUTH } from './reducers/ONCHANGE_USER_PASSWORD_AUTH'
import { ONCHANGE_USER_PASSWORD_AUTH_2 } from './reducers/ONCHANGE_USER_PASSWORD_AUTH_2'
import { PLUS_QUESTION_SLIDE } from './reducers/PLUS_QUESTION_SLIDE'
import { SAVE_ANALYTICS_SUCCESS } from './reducers/SAVE_ANALYTICS_SUCCESS'
import { SELECT_COURSE_MODULE } from './reducers/SELECT_COURSE_MODULE'
import { SELECT_LANGUAGE_APP } from './reducers/SELECT_LANGUAGE_APP'
import { SELECT_SKILLS_EXPERTISE } from './reducers/SELECT_SKILLS_EXPERTISE'
import { SELECT_USER_COUNTRY } from './reducers/SELECT_USER_COUNTRY'
import { SELECT_USER_GENDER } from './reducers/SELECT_USER_GENDER'
import { SELECT_USER_LANGUAGES } from './reducers/SELECT_USER_LANGUAGES'
import { SELECT_USER_MEDIA } from './reducers/SELECT_USER_MEDIA'
import { SEP_INPUT_AGE_FROM_REQUIRED } from './reducers/SEP_INPUT_AGE_FROM_REQUIRED'
import { SEP_INPUT_AGE_TO_REQUIRED } from './reducers/SEP_INPUT_AGE_TO_REQUIRED'
import { SEP_INPUT_DESCRIPTION_REQUIRED } from './reducers/SEP_INPUT_DESCRIPTION_REQUIRED'
import { SEP_SELECT_COUNTRY_REQUIRED } from './reducers/SEP_SELECT_COUNTRY_REQUIRED'
import { SEP_SELECT_GENDER_REQUIRED } from './reducers/SEP_SELECT_GENDER_REQUIRED'
import { SEP_SELECT_LANGUAGE_REQUIRED } from './reducers/SEP_SELECT_LANGUAGE_REQUIRED'
import { SEP_SELECT_MEDIA_REQUIRED } from './reducers/SEP_SELECT_MEDIA_REQUIRED'
import { SEP_SELECT_SKILLS_OFFERED } from './reducers/SEP_SELECT_SKILLS_OFFERED'
import { SEP_SELECT_SKILLS_REQUIRED } from './reducers/SEP_SELECT_SKILLS_REQUIRED'
import { SEP_SELECT_SORT_BY } from './reducers/SEP_SELECT_SORT_BY'
import { SET_AUTH_AWS_COGNITO_USER_DATA } from './reducers/SET_AUTH_AWS_COGNITO_USER_DATA'
import { SET_COURSE_ID_ACTIVE } from './reducers/SET_COURSE_ID_ACTIVE'
import { SET_COURSES } from './reducers/SET_COURSES'
import { SET_IS_ADVANCED_SEARCH } from './reducers/SET_IS_ADVANCED_SEARCH'
import { SET_MODAL_FRAMES } from './reducers/SET_MODAL_FRAMES'
import { SET_MODULE_ID_ACTIVE } from './reducers/SET_MODULE_ID_ACTIVE'
import { SET_OAUTH_FB_SCRIPT_STATE } from './reducers/SET_OAUTH_FB_SCRIPT_STATE'
import { SET_OAUTH_GOOGLE_SCRIPT_STATE } from './reducers/SET_OAUTH_GOOGLE_SCRIPT_STATE'
import { SET_OAUTH_STAGE } from './reducers/SET_OAUTH_STAGE'
import { SET_OAUTH_VK_SCRIPT_STATE } from './reducers/SET_OAUTH_VK_SCRIPT_STATE'
import { SET_QUESTION_SLIDE } from './reducers/SET_QUESTION_SLIDE'
import { SET_SEARCH_INPUT } from './reducers/SET_SEARCH_INPUT'
import { SET_SIDE_NAVIGATION_LEFT } from './reducers/SET_SIDE_NAVIGATION_LEFT'
import { SET_STORE_STATE } from './reducers/SET_STORE_STATE'
import { SET_THEME } from './reducers/SET_THEME'
import { SET_USER_PROFILE } from './reducers/SET_USER_PROFILE'
import { SET_USERS } from './reducers/SET_USERS'
import { TOGGLE_IS_DOCUMENT_ADDED } from './reducers/TOGGLE_IS_DOCUMENT_ADDED'
import { TOGGLE_LOADER_OVERLAY } from './reducers/TOGGLE_LOADER_OVERLAY'
import { TOGGLE_MEDIA_LOADED } from './reducers/TOGGLE_MEDIA_LOADED'
import { TOGGLE_START_COURSE } from './reducers/TOGGLE_START_COURSE'
import { rootStoreDefault } from './rootStoreDefault'

export type IndexReducerType =
  | Reducer<RootStoreType, Action<any>>
  | ReducersMapObject<RootStoreType, Action<any>>

export const indexReducer: IndexReducerType = (
  store = rootStoreDefault,
  action = { type: 'DEFAULT' }
) => {
  // @ts-ignore
  const { type, data } = action

  const output: Record<string, any> = {
    TEMPLATE,
    SET_IS_LOADED_LOCAL_STORAGE_STORE_STATE,
    SET_STORE_STATE,
    SET_AUTH_AWS_COGNITO_USER_DATA,
    SET_COURSE_ID_ACTIVE,
    SET_MODULE_ID_ACTIVE,
    SET_COURSES,
    GET_COGNITO_TOKENS_SUCCESS,
    SET_USERS,
    SELECT_USER_MEDIA,
    SELECT_USER_GENDER,
    ONCHANGE_USER_BIRTH_YEAR,
    SELECT_USER_LANGUAGES,
    SELECT_USER_COUNTRY,
    ONCHANGE_USER_NAME_FIRST,
    ONCHANGE_USER_INFO_ABOUT,
    SELECT_SKILLS_EXPERTISE,
    GET_AVATAR_PATH,
    SET_SEARCH_INPUT,
    SET_IS_ADVANCED_SEARCH,
    SEP_SELECT_SKILLS_OFFERED,
    SEP_SELECT_SKILLS_REQUIRED,
    SEP_SELECT_COUNTRY_REQUIRED,
    SEP_SELECT_LANGUAGE_REQUIRED,
    SEP_INPUT_AGE_FROM_REQUIRED,
    SEP_INPUT_AGE_TO_REQUIRED,
    SEP_SELECT_GENDER_REQUIRED,
    SEP_SELECT_MEDIA_REQUIRED,
    SEP_INPUT_DESCRIPTION_REQUIRED,
    SEP_SELECT_SORT_BY,
    SET_THEME,
    SET_OAUTH_STAGE,
    SET_OAUTH_FB_SCRIPT_STATE,
    SET_OAUTH_VK_SCRIPT_STATE,
    SET_OAUTH_GOOGLE_SCRIPT_STATE,
    SET_USER_PROFILE,
    ONCHANGE_USER_NAME,
    ONCHANGE_USER_EMAIL,
    ONCHANGE_USER_PASSWORD_AUTH,
    ONCHANGE_USER_PASSWORD_AUTH_2,
    SET_MODAL_FRAMES,
    GET_COURSE_QUERY_PR_QN,
    SAVE_ANALYTICS_SUCCESS,
    TOGGLE_MEDIA_LOADED,
    TOGGLE_START_COURSE,
    ONCHANGE_SEARCH_INPUT,
    CHANGE_NUM_QUESTIONS_IN_SLIDE,
    SELECT_LANGUAGE_APP,
    TOGGLE_LOADER_OVERLAY,
    TOGGLE_IS_DOCUMENT_ADDED,
    ADD_DOCUMENT,
    SET_QUESTION_SLIDE,
    PLUS_QUESTION_SLIDE,
    ONCHANGE_EMAIL_CC,
    ONCHANGE_EMAIL_TO,
    ONCHANGE_USER_NAME_NICK,
    ONCHANGE_FIRST_NAME_MODAL,
    ONCHANGE_MIDDLE_NAME_MODAL,
    ONCHANGE_LAST_NAME_MODAL,
    GET_ANSWERS_DEFAULT,
    SELECT_COURSE_MODULE,
    CLICK_CHECK,
    GET_COURSES_SUCCESS,
    SET_SIDE_NAVIGATION_LEFT,
  }

  return output[type] ? output[type](store, data) : store
}
